# Generated by Django 5.1.1 on 2024-10-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='Bookmark',
        ),
    ]
