# Generated by Django 5.1.2 on 2024-11-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bookmark_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='diagnosis',
            new_name='disease',
        ),
    ]
