# Generated by Django 5.1.2 on 2024-11-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_diagnosis_scan_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='status',
        ),
    ]
