# Generated by Django 5.1.2 on 2024-12-06 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_scan_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='img',
            field=models.ImageField(upload_to='storage/scans'),
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('image', models.ImageField(null=True, upload_to='storage/trees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Tree',
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='tree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.tree'),
        ),
    ]
