# Generated by Django 5.1.2 on 2024-12-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_scan_img_tree_scan_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tree'),
        ),
    ]
