# Generated by Django 5.1.2 on 2024-12-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tree_last_predicted_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='img',
            field=models.ImageField(max_length=500, upload_to='storage/scans'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='storage/trees'),
        ),
    ]
